version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
        registry_external_url 'http://gitlab:5050'
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5050
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '5050:5050'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    networks:
      - gitlab
networks: 
  gitlab: