version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab'
        registry_external_url 'https://gitlab:5050'
        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5050
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.local.p.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.p.key"
        registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.local.p.crt"
        registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.p.key"
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '5050:5050'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    networks:
      - gitlab
networks: 
  gitlab: